-- MOM VILLAGE — MIGRATION 10
-- Loads the locked 9-phase Weekly Care Chart content into weekly_care_chart_content.
-- Source: Weekly Care Chart - All 9 Phases (LOCKED).docx, ChatGPT-reviewed and
-- independently fact-checked (ACOG, CDC Hear Her, WHO, NHM India, LactMed).
-- Run this once — running twice will duplicate rows (no unique constraint enforces
-- one-time loading, so check row count first if re-running).

insert into weekly_care_chart_content
  (week_number, phase_key, section, delivery_type, health_flag, time_option, title, body, sort_order)
values
  (-33, 'first_trimester', 'body', 'any', 'none', '5', '5 min', 'Slow breathing and a comfortable pelvic-floor check-in — include full relaxation, not only squeezing.', 1),
  (-33, 'first_trimester', 'body', 'any', 'none', '15', '15 min', 'A gentle outdoor walk or seated prenatal stretches for shoulders, hips, and lower back.', 2),
  (-33, 'first_trimester', 'body', 'any', 'none', '30', '30 min', 'A walk, stationary cycling, or beginner prenatal yoga if it feels good and your maternity clinician has not advised limits.', 3),
  (-33, 'first_trimester', 'body', 'any', 'none', 'any', 'Note', 'Start slowly if exercise is new. Choose cool conditions, avoid overheating, and stop rather than pushing through pain, dizziness, or unusual symptoms.', 4),
  (-33, 'first_trimester', 'food', 'any', 'none', 'any', 'Nausea days', 'Try dry toast, khichdi, ginger in food or tea if it agrees with you, and small frequent meals instead of three large ones.', 1),
  (-33, 'first_trimester', 'food', 'any', 'none', 'any', 'Protein that sits well', 'Dal, paneer, eggs, curd, or moong can be enough. Keep food simple rather than forcing a “perfect” plate.', 2),
  (-33, 'first_trimester', 'food', 'any', 'none', 'any', 'Supplements and fluids', 'Continue prescribed folic acid and other medicines. Contact your doctor if you cannot keep fluids down, are very dizzy, pass very dark urine, or are losing weight.', 3),
  (-33, 'first_trimester', 'mind', 'any', 'none', '5', '5 min', 'A short breathing or grounding practice for anxiety-spike days.', 1),
  (-33, 'first_trimester', 'mind', 'any', 'none', '15', '15 min', 'Journal: “How am I actually feeling today, not how I think I should feel?”', 2),
  (-33, 'first_trimester', 'mind', 'any', 'none', '30', '30 min', 'A guided meditation about transition — becoming, not yet arrived.', 3),
  (-33, 'first_trimester', 'mind', 'any', 'none', 'any', 'Note', 'It is okay to set a boundary with unsolicited advice or negativity. Protecting your peace is part of care.', 4),
  (-33, 'first_trimester', 'skin', 'any', 'none', 'any', 'Basics', 'Gentle cleanser and SPF every day; simple is enough.', 1),
  (-33, 'first_trimester', 'skin', 'any', 'none', 'any', 'Actives', 'Azelaic acid, niacinamide, vitamin C, benzoyl peroxide, glycolic acid, and limited topical salicylic acid are commonly discussed options, but confirm a new product with your obstetrician or dermatologist.', 2),
  (-33, 'first_trimester', 'skin', 'any', 'none', 'any', 'Avoid', 'Do not use oral or topical retinoids in pregnancy. Avoid peels, large-area/high-strength treatments, or new prescription products unless your doctor specifically advises them.', 3),
  (-20, 'second_trimester', 'body', 'any', 'none', '5', '5 min', 'Standing pelvic tilts, gentle side stretches, and a relaxed pelvic-floor check-in.', 1),
  (-20, 'second_trimester', 'body', 'any', 'none', '15', '15 min', 'Prenatal yoga or a brisk but conversational walk.', 2),
  (-20, 'second_trimester', 'body', 'any', 'none', '30', '30 min', 'Swimming, stationary cycling, or a structured prenatal fitness class if it is comfortable and suitable for you.', 3),
  (-20, 'second_trimester', 'body', 'any', 'none', 'any', 'Note', 'As your body changes, use side-lying or propped positions if lying flat makes you dizzy, sick, or breathless. Keep avoiding falls and overheating.', 4),
  (-20, 'second_trimester', 'food', 'any', 'none', 'any', 'Steady energy', 'Whole grains, dals, seasonal fruit, vegetables, nuts prepared safely, and regular meals can help with energy swings.', 1),
  (-20, 'second_trimester', 'food', 'any', 'none', 'any', 'Bone and blood support', 'Include calcium-rich foods such as dairy, ragi, or sesame if they suit you, and continue prescribed iron/calcium plans.', 2),
  (-20, 'second_trimester', 'food', 'any', 'none', 'any', 'Note', 'Persistent fatigue, breathlessness at rest, or marked paleness deserves a call to your doctor rather than simply “pushing through.”', 3),
  (-20, 'second_trimester', 'mind', 'any', 'none', '5', '5 min', 'A body-gratitude practice: notice what your body is doing, not only how it looks.', 1),
  (-20, 'second_trimester', 'mind', 'any', 'none', '15', '15 min', 'Journal about what is shifting in relationships, work, or identity.', 2),
  (-20, 'second_trimester', 'mind', 'any', 'none', '30', '30 min', 'A longer meditation or a practical conversation with your partner/family about the support you will need later.', 3),
  (-20, 'second_trimester', 'mind', 'any', 'none', 'any', 'Note', 'You set the terms of how much you share, with whom, and when.', 4),
  (-20, 'second_trimester', 'skin', 'any', 'none', 'any', 'Basics', 'Continue gentle cleanser, SPF, and fragrance-free moisturiser if stretching skin feels itchy.', 1),
  (-20, 'second_trimester', 'skin', 'any', 'none', 'any', 'Normal changes', 'Melasma and linea nigra are common. A hat and broad-spectrum sunscreen help stop melasma from darkening.', 2),
  (-20, 'second_trimester', 'skin', 'any', 'none', 'any', 'Call your doctor', 'Let your clinician know about intense itching, especially on palms or soles, a widespread rash, blisters, or itching that keeps you awake.', 3),
  (-6, 'third_trimester', 'body', 'any', 'none', '5', '5 min', 'Slow breathing for labour prep and pelvic-floor relaxation — learning to release, not just contract.', 1),
  (-6, 'third_trimester', 'body', 'any', 'none', '15', '15 min', 'A gentle walk or stretches focused on hips, upper back, and lower back.', 2),
  (-6, 'third_trimester', 'body', 'any', 'none', '30', '30 min', 'Prenatal yoga or swimming may be comfortable; shorten or change the plan as balance and energy shift.', 3),
  (-6, 'third_trimester', 'body', 'any', 'none', 'any', 'Note', 'Avoid fall-risk activity. Stop and get advice for pain, bleeding, fluid leakage, regular painful contractions, severe headache, visual changes, chest pain, fainting, or breathlessness before exertion.', 4),
  (-6, 'third_trimester', 'food', 'any', 'none', 'any', 'Comfort', 'Smaller, frequent meals can help heartburn or fullness. Fibre, fluids, and gentle movement may help constipation.', 1),
  (-6, 'third_trimester', 'food', 'any', 'none', 'any', 'Basics', 'Continue prescribed iron, calcium, protein-rich foods, and any plan for gestational diabetes, anaemia, blood pressure, or thyroid care.', 2),
  (-6, 'third_trimester', 'food', 'any', 'none', 'any', 'Movement', 'Contact your maternity team for a clear reduction in your baby''s usual movement; do not rely on a fixed number or a home heartbeat device.', 3),
  (-6, 'third_trimester', 'mind', 'any', 'none', '5', '5 min', 'A calming practice for labour worries: a few slow breaths, a hand on your belly, or a grounding phrase.', 1),
  (-6, 'third_trimester', 'mind', 'any', 'none', '15', '15 min', 'Write down questions or preferences for the birth, focused on preparation rather than perfection.', 2),
  (-6, 'third_trimester', 'mind', 'any', 'none', '30', '30 min', 'Talk with your support person about practical help during labour and the first weeks at home.', 3),
  (-6, 'third_trimester', 'mind', 'any', 'none', 'any', 'Note', 'You do not need to feel only excited. Fear, tenderness, impatience, and joy can all be present.', 4),
  (-6, 'third_trimester', 'skin', 'any', 'none', 'any', 'Stretch marks', 'They may appear on belly, hips, thighs, breasts, or chest. Genetics plays a larger role than products; moisturiser can still improve comfort.', 1),
  (-6, 'third_trimester', 'skin', 'any', 'none', 'any', 'Swelling', 'Mild ankle/foot swelling can be common. Rest with feet up when comfortable, but report sudden or severe swelling of face/hands, especially with headache or vision changes.', 2),
  (-6, 'third_trimester', 'skin', 'any', 'none', 'any', 'Continue', 'Keep skincare gentle and continue avoiding retinoids and unapproved high-strength treatments.', 3),
  (3, 'early_healing', 'body', 'any', 'none', '5', '5 min', 'Diaphragmatic breathing, posture awareness, and a gentle pelvic-floor connection if it feels comfortable.', 1),
  (3, 'early_healing', 'body', 'any', 'none', '15', '15 min', 'A short, slow walk when you feel ready; there is no fixed day. Gentle movement may be encouraged early after an uncomplicated vaginal birth.', 2),
  (3, 'early_healing', 'body', 'any', 'none', '30', '30 min', 'Only if your own team has cleared it and you feel well; otherwise, shorter is enough.', 3),
  (3, 'early_healing', 'body', 'c_section', 'none', 'any', 'After caesarean or complications', 'Follow your surgical/obstetric team''s plan. Gentle walking may still be encouraged, but build gradually. Avoid lifting beyond your clinician''s advice, roll to your side to get up, and stop for pain, pelvic pressure, incision discomfort, or increasing bleeding.', 4),
  (3, 'early_healing', 'food', 'any', 'none', 'any', 'Healing meals', 'Use easy iron- and protein-rich meals: dals, leafy greens, eggs, dairy, and meat/fish where eaten. Accept help with food.', 1),
  (3, 'early_healing', 'food', 'any', 'none', 'any', 'If breastfeeding', 'Eat regular, nourishing meals and drink to thirst. You do not need a punishing “breastfeeding diet” or detox.', 2),
  (3, 'early_healing', 'food', 'any', 'none', 'any', 'Breast support', 'Seek help promptly for painful/damaged nipples, a red/hot painful breast with fever, or worries about feeding, milk supply, or baby''s latch.', 3),
  (3, 'early_healing', 'mind', 'any', 'none', '5', '5 min', 'Breathe, sit in daylight, or step outside briefly if someone can hold the baby.', 1),
  (3, 'early_healing', 'mind', 'any', 'none', '15', '15 min', 'A guided rest or simply lying down without a task, even if sleep does not happen.', 2),
  (3, 'early_healing', 'mind', 'any', 'none', '30', '30 min', 'Connect with one person who makes you feel supported, not judged.', 3),
  (3, 'early_healing', 'mind', 'any', 'none', 'any', 'Mental health', 'Baby blues can bring tearfulness and mood swings in the first two weeks. Persistent or intense sadness, anxiety, anger, hopelessness, panic, or feeling unable to cope can be postpartum depression or anxiety — tell your doctor. Seek emergency help for thoughts of harm, confusion, extreme agitation, or hearing/seeing things others do not.', 4),
  (3, 'early_healing', 'skin', 'any', 'none', 'any', 'Incision', 'If you had a caesarean birth, follow your team''s wound-care instructions. Call for increasing redness, warmth, swelling, discharge, opening of the wound, fever, or worsening pain.', 1),
  (3, 'early_healing', 'skin', 'any', 'none', 'any', 'Simple care', 'Keep skincare gentle and familiar. This is not the time to trial a new active product.', 2),
  (3, 'early_healing', 'skin', 'any', 'none', 'any', 'Hair', 'Hair shedding has not usually started yet; if it comes later, it is commonly temporary.', 3),
  (9, 'finding_rhythm', 'body', 'any', 'none', '5', '5 min', 'Continue comfortable pelvic-floor work and gentle core breathing.', 1),
  (9, 'finding_rhythm', 'body', 'any', 'none', '15', '15 min', 'Walk a little longer or brisker if it feels good.', 2),
  (9, 'finding_rhythm', 'body', 'any', 'none', '30', '30 min', 'Light strength work or gentle postnatal yoga, progressing only when symptoms stay settled.', 3),
  (9, 'finding_rhythm', 'body', 'any', 'none', 'any', 'Modify, do not push', 'There is no blanket ban on every core exercise, but stop or modify any movement that causes pain, heaviness, leaking urine, incision discomfort, or midline doming. A pelvic-health physiotherapist can tailor core and pelvic-floor work.', 4),
  (9, 'finding_rhythm', 'food', 'any', 'none', 'any', 'Recovery', 'Continue iron and protein-rich foods if prescribed or needed for recovery.', 1),
  (9, 'finding_rhythm', 'food', 'any', 'none', 'any', 'If breastfeeding', 'Prioritise hydration and steady meals over skipping food when busy.', 2),
  (9, 'finding_rhythm', 'food', 'any', 'none', 'any', 'No deadline', 'This is a good time to notice what supports your energy — not a time to make weight loss the project.', 3),
  (9, 'finding_rhythm', 'mind', 'any', 'none', '5', '5 min', 'A grounding check-in: “How am I, really, today?”', 1),
  (9, 'finding_rhythm', 'mind', 'any', 'none', '15', '15 min', 'Journal or voice-note the wins, even very small ones.', 2),
  (9, 'finding_rhythm', 'mind', 'any', 'none', '30', '30 min', 'Reconnect with something outside “mother” — a hobby, friend, or interest that is yours.', 3),
  (9, 'finding_rhythm', 'mind', 'any', 'none', 'any', 'Note', 'If the fog has not lifted, or persistent low mood, anxiety, rage, panic, or overwhelm is present, tell your doctor. Postpartum depression and anxiety can first show up later too.', 4),
  (9, 'finding_rhythm', 'skin', 'any', 'none', 'any', 'Hair', 'Shedding may begin around 2–4 months after birth. This common temporary shedding is called telogen effluvium and usually settles gradually.', 1),
  (9, 'finding_rhythm', 'skin', 'any', 'none', 'any', 'Ask for advice', 'Seek help for bald patches, scalp pain/rash, marked fatigue, or shedding that does not improve over time.', 2),
  (9, 'finding_rhythm', 'skin', 'any', 'none', 'any', 'Routine', 'Keep the basics gentle and consistent.', 3),
  (19, 'rebuilding', 'body', 'any', 'none', '5', '5 min', 'Pelvic-floor and core check-ins: comfortable, controlled, and symptom-free.', 1),
  (19, 'rebuilding', 'body', 'any', 'none', '15', '15 min', 'A brisk walk or bodyweight strength circuit, progressing slowly.', 2),
  (19, 'rebuilding', 'body', 'any', 'none', '30', '30 min', 'Structured postnatal workouts, swimming, or cycling if your body is tolerating the build-up well.', 3),
  (19, 'rebuilding', 'body', 'any', 'none', 'any', 'Progression', 'There is no universal 12-week return-to-high-intensity deadline. Build intensity one step at a time and seek advice for pain, heaviness, leaking, doming, dizziness, or unusual fatigue.', 4),
  (19, 'rebuilding', 'food', 'any', 'none', 'any', 'Family-meal energy', 'Keep easy meals available for yourself as well as the family — protein, fibre, iron-rich foods, fruit/vegetables, and enough fluids for your day.', 1),
  (19, 'rebuilding', 'food', 'any', 'none', 'any', 'Around 6 months', 'If baby is approaching six months and complementary feeding is beginning on your paediatrician''s guidance, keep your own meals simple and nourishing too.', 2),
  (19, 'rebuilding', 'food', 'any', 'none', 'any', 'Feeding changes', 'If breastfeeding is winding down or has stopped, appetite and fluid needs may shift. There is nothing to “make up” for; eat to how you feel.', 3),
  (19, 'rebuilding', 'mind', 'any', 'none', '5', '5 min', 'A moment of stillness, however it fits.', 1),
  (19, 'rebuilding', 'mind', 'any', 'none', '15', '15 min', 'Name one thing that has genuinely become easier.', 2),
  (19, 'rebuilding', 'mind', 'any', 'none', '30', '30 min', 'Reconnect with people, hobbies, or routines that were paused.', 3),
  (19, 'rebuilding', 'mind', 'any', 'none', 'any', 'Note', 'Persistent low mood, anxiety, intrusive thoughts, or feeling unable to cope still deserves support. Care remains just as valid months after birth.', 4),
  (19, 'rebuilding', 'skin', 'any', 'none', 'any', 'Hair', 'Shedding often peaks around month four and then eases gradually.', 1),
  (19, 'rebuilding', 'skin', 'any', 'none', 'any', 'Routine', 'Reassess your routine as hormones settle. If breastfeeding, check all prescription or strong active products first and never apply medicated products to the nipple/areola or skin baby may mouth.', 2),
  (19, 'rebuilding', 'skin', 'any', 'none', 'any', 'Retinoids', 'Do not restart oral retinoids without specialist advice. For topical retinoids while breastfeeding, ask your clinician and keep use away from baby contact.', 3),
  (39, 'settling_into_strength', 'body', 'any', 'none', '5', '5 min', 'A quick mobility or stretch break.', 1),
  (39, 'settling_into_strength', 'body', 'any', 'none', '15', '15 min', 'A walk, home workout, or movement that fits around baby''s schedule.', 2),
  (39, 'settling_into_strength', 'body', 'any', 'none', '30', '30 min', 'A structured workout of your choice, increased gradually if you are symptom-free.', 3),
  (39, 'settling_into_strength', 'body', 'any', 'none', 'any', 'Note', 'Caring for a mobile baby counts as activity too. It does not need to be separate from a “workout.” Persistent pain, leakage, pelvic heaviness, scar discomfort, or fatigue still deserves care.', 4),
  (39, 'settling_into_strength', 'food', 'any', 'none', 'any', 'Rhythm', 'Return to a steady, varied eating rhythm that works for your household.', 1),
  (39, 'settling_into_strength', 'food', 'any', 'none', 'any', 'If breastfeeding', 'Continue regular meals, hydration, and any clinician-recommended supplements.', 2),
  (39, 'settling_into_strength', 'food', 'any', 'none', 'any', 'Sustainable', 'Avoid food rules that leave you depleted; energy for parenting is a real health need.', 3),
  (39, 'settling_into_strength', 'mind', 'any', 'none', '5', '5 min', 'A quick check-in on how you are doing, not only how baby is doing.', 1),
  (39, 'settling_into_strength', 'mind', 'any', 'none', '15', '15 min', 'Something purely for your own enjoyment.', 2),
  (39, 'settling_into_strength', 'mind', 'any', 'none', '30', '30 min', 'Rebuild a friendship, routine, or identity piece that matters to you.', 3),
  (39, 'settling_into_strength', 'mind', 'any', 'none', 'any', 'Note', 'Support does not expire after the early postpartum months. Reach out whenever mood, anxiety, sleep, trauma, or overwhelm is getting in the way of daily life.', 4),
  (39, 'settling_into_strength', 'skin', 'any', 'none', 'any', 'Hair', 'Hair density may be recovering, though timing varies from person to person.', 1),
  (39, 'settling_into_strength', 'skin', 'any', 'none', 'any', 'Routine', 'A fuller skincare routine can be reasonable; if you are breastfeeding, check new medicines/strong actives and keep them away from baby contact.', 2),
  (39, 'settling_into_strength', 'skin', 'any', 'none', 'any', 'Sun', 'SPF remains a useful daily basic, especially with more outdoor time.', 3),
  (78, 'sustainable_rhythms', 'body', 'any', 'none', '5', '5 min', 'A stretch break.', 1),
  (78, 'sustainable_rhythms', 'body', 'any', 'none', '15', '15 min', 'A walk, home workout, or active play with your toddler.', 2),
  (78, 'sustainable_rhythms', 'body', 'any', 'none', '30', '30 min', 'Your regular routine — whatever “fit” means for you now.', 3),
  (78, 'sustainable_rhythms', 'body', 'any', 'none', 'any', 'Note', 'There is no universal recovery timetable. Ongoing pelvic pain, leakage, prolapse symptoms, difficult periods, sexual discomfort, or fatigue are still medical concerns worth raising.', 4),
  (78, 'sustainable_rhythms', 'food', 'any', 'none', 'any', 'Family meals', 'Cook once for the family where possible, adapting texture and seasoning for your toddler.', 1),
  (78, 'sustainable_rhythms', 'food', 'any', 'none', 'any', 'Your needs', 'Your nutrition is your own — and if you continue breastfeeding, are newly pregnant, or manage a health condition, your needs may be different again.', 2),
  (78, 'sustainable_rhythms', 'food', 'any', 'none', 'any', 'Sustainable', 'Eat enough for your real day rather than chasing an old version of your body.', 3),
  (78, 'sustainable_rhythms', 'mind', 'any', 'none', '5', '5 min', 'A breathing pause amid toddler chaos.', 1),
  (78, 'sustainable_rhythms', 'mind', 'any', 'none', '15', '15 min', 'Something that is only for you and unrelated to parenting.', 2),
  (78, 'sustainable_rhythms', 'mind', 'any', 'none', '30', '30 min', 'Nurture a friendship, hobby, or interest that helps you feel like yourself.', 3),
  (78, 'sustainable_rhythms', 'mind', 'any', 'none', 'any', 'Note', 'Identity questions can resurface here. “Who am I outside of mum?” is a common question, not a sign something is wrong.', 4),
  (78, 'sustainable_rhythms', 'skin', 'any', 'none', 'any', 'Routine', 'Keep the routine that is working; small maintenance is enough.', 1),
  (78, 'sustainable_rhythms', 'skin', 'any', 'none', 'any', 'Sun', 'Sun protection remains a daily basic with more outdoor toddler time.', 2),
  (78, 'sustainable_rhythms', 'skin', 'any', 'none', 'any', 'Check first', 'If breastfeeding continues, apply the same care with prescription products or strong actives: check first and keep products away from baby contact.', 3),
  (130, 'rhythm_year_three', 'body', 'any', 'none', '5', '5 min', 'A stretch break.', 1),
  (130, 'rhythm_year_three', 'body', 'any', 'none', '15', '15 min', 'A walk or home workout.', 2),
  (130, 'rhythm_year_three', 'body', 'any', 'none', '30', '30 min', 'Your regular routine, whatever that looks like now.', 3),
  (130, 'rhythm_year_three', 'body', 'any', 'none', 'any', 'Note', 'Choose movement for strength, steadiness, enjoyment, sleep, or stress relief — not because your body owes anyone a “bounce back.”', 4),
  (130, 'rhythm_year_three', 'food', 'any', 'none', 'any', 'Pattern', 'Continue varied family-meal patterns that support your energy.', 1),
  (130, 'rhythm_year_three', 'food', 'any', 'none', 'any', 'No special deadline', 'Nothing needs to be “completed” at your child''s third birthday. Your health needs deserve attention whenever they arise.', 2),
  (130, 'rhythm_year_three', 'mind', 'any', 'none', '5', '5 min', 'A grounding pause.', 1),
  (130, 'rhythm_year_three', 'mind', 'any', 'none', '15', '15 min', 'Reflect on how far you have come since this journey began.', 2),
  (130, 'rhythm_year_three', 'mind', 'any', 'none', '30', '30 min', 'Protect time for yourself, a friendship, or a goal that belongs only to you.', 3),
  (130, 'rhythm_year_three', 'mind', 'any', 'none', 'any', 'Note', 'Mixed feelings as the third birthday approaches are normal. Support remains available whenever you need it — no expiry date.', 4),
  (130, 'rhythm_year_three', 'skin', 'any', 'none', 'any', 'Routine', 'A steady-state routine is enough: cleanse, moisturise if you like, and use SPF.', 1),
  (130, 'rhythm_year_three', 'skin', 'any', 'none', 'any', 'Care', 'New or changing rashes, moles, hair/scalp symptoms, or a skin concern that affects confidence or comfort is worth discussing with a dermatologist.', 2);