-- Care Chart week-by-week rebuild — Your Rhythm, Year Three Part 1 content, 2026-07-29.
--
-- Eighth batch of the postpartum week-by-week build, first of two parts
-- closing the entire rebuild. Covers postpartum weeks 105-130 (roughly
-- 2 years to 2 years 6 months). No schema changes needed beyond
-- migration_43 (mental_health_note, already added for Sustainable Rhythms
-- Part 2). Week-number convention unchanged: postpartum week 105 =
-- week_number 145, week 130 = week_number 170.
--
-- Batching confirmed with Roop via AskUserQuestion: this 52-week phase
-- ("Your rhythm, year three," weeks 105-156) split into two 26-week
-- batches, same size as every batch since Settling into Strength and
-- matching how Sustainable Rhythms was split. This is Part 1; Part 2
-- (weeks 131-156, week_number 171-196) will carry through to the third
-- birthday, closing the entire postpartum rebuild.
--
-- Claude drafted the full 26-week base version (see "Care Chart — Your
-- Rhythm Year Three Part 1 — Base Draft (Weeks 105-130).md"), continuing
-- every decision established in Sustainable Rhythms Part 2: no "Choose
-- your recovery route" block (delivery-type differences are long resolved
-- by two years postpartum); real, named coping techniques woven into every
-- week's Reset section per Roop's standing instruction on including mental
-- health methods in every draft; one dedicated general-wellbeing check-in
-- week (120, "How are you, really," continuing the established ~12-15-week
-- cadence from weeks 88/100 in the prior batch); and condition_notes on the
-- closing week (130, all four flags), matching the pattern every prior
-- batch's closing week has followed even when it wasn't the true end of
-- the whole phase.
--
-- **Different process this batch, flagged transparently.** Roop uploaded a
-- file back for review ("preview.md") that turned out to be byte-for-byte
-- identical to Claude's own base draft (diffed directly — 2421 lines,
-- zero differences) — the external AI-app review pass evidently didn't
-- happen this time, rather than silently treating it as reviewed. Flagged
-- this to Roop via AskUserQuestion; she confirmed locking Claude's own
-- base draft as final for this batch rather than waiting for a re-upload.
-- Content therefore carries the same verification standard as every prior
-- batch's *drafting* stage (grounded in this project's established,
-- already-verified claims — GDM/high-BP/thyroid/PCOS long-term follow-up
-- reminders match what's already been independently verified in earlier
-- batches, no new numeric/clinical claims introduced this batch requiring
-- fresh verification) but has not been through the second-AI-app review
-- pass every other batch in this series has had.
--
-- Content parsed programmatically from Claude's own markdown draft (not
-- hand-transcribed, and not pandoc-converted since no docx existed this
-- time — a new parser, parse_yr3p1.py, was adapted from parse_sr1.py's
-- dash-underlined-header format, matching the draft's own authored
-- structure) and round-trip validated via the same state-machine
-- SQL-literal parser used for every prior migration: 53 jsonb blocks, zero
-- errors. All 26 week_numbers (145-170) present, no gaps or duplicates.
-- Zero stray backslashes (checked programmatically). Parens and quotes
-- balanced.
--
-- Next batch: Your rhythm, year three Part 2 (postpartum weeks 131-156,
-- week_number 171-196) — closes the entire postpartum week-by-week rebuild
-- at the third birthday.

insert into care_chart_week_content (
  week_number, trimester, theme_title, mantra, priority, journey,
  what_you_may_notice, move, nourish, hydration_goal, feeding_comfort,
  rest_support, reset, care_for_yourself, your_corner, support_moment,
  celebrate_this_week, mental_health_note, for_your_care_team, condition_notes
) values
(
  145,
  'postpartum',
  'Into Year Three',
  'Two years down. You know more than you think you do.',
  'Notice how much more confident you''ve become at this, even on hard days.',
  'Crossing into the third year often brings a quieter kind of confidence — you''ve done two full years of this, through everything they held. This week is a gentle acknowledgment of that, before the specific themes of this final stretch begin.',
  ARRAY['A settled rhythm that took two years to build','Occasional disbelief at how much has changed since the beginning','A more verbal, opinionated child changing the shape of your days','Continued fatigue, even with more established routines']::text[],
  '{"focus": "Whatever routine has genuinely stuck for you by now.", "tiers": {"heavy": "A few stretches, wherever you are.", "steady": "Your go-to walk or short session.", "feeling_good": "Your established routine, at whatever level you''ve built to."}, "mood_adjustment": "By this stage you likely know your own patterns well — trust them over any generic guidance here.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "Box breathing: in for 4, hold for 4, out for 4, hold for 4. A reliable reset, worth returning to whenever things feel like too much.", "a_little_low": "Values-based action: pick one small thing today that reflects who you want to be as a mother, regardless of mood — it can shift how a hard day feels.", "okay": "Notice today as simply okay — not every day needs to be remarkable.", "good": "Let a good day be good, fully.", "really_good": "Enjoy the confidence of two years in — you''ve earned it."}'::jsonb,
  'Whatever self-care ritual has genuinely stuck for you by now, keep it going.',
  'Reflect on how far you''ve come since the very beginning.',
  'Tell someone who''s been there since early on how much their support has meant.',
  'Two years in, and you''re still showing up, still learning, still growing alongside her. That''s real.',
  'However today felt, support isn''t limited to hard weeks — Mental health & support is there whenever it''s useful to you.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  146,
  'postpartum',
  'Bigger Words, Bigger Negotiations',
  'More words means more negotiating — that''s growth, not defiance.',
  'Notice your own patience with the new back-and-forth her growing vocabulary brings.',
  'By two, many toddlers have a real vocabulary and start using it to negotiate, argue, and assert opinions — about clothes, food, everything. It''s a genuine developmental leap, and it can also be exhausting in a very specific, new way.',
  ARRAY['More back-and-forth negotiation over small daily decisions','A shift from physical tantrums to more verbal pushback','Pride in her growing communication, mixed with fatigue from the negotiating','A need for new strategies as old ones stop working']::text[],
  '{"focus": "Something that helps you find patience through repetition.", "tiers": {"heavy": "Slow neck and shoulder rolls — tension from negotiating all day settles there.", "steady": "A walk with music or a podcast, a mental break from words.", "feeling_good": "Whatever cardio or strength session helps you feel steady."}, "mood_adjustment": "If patience is thin from a day of negotiating, movement that doesn''t require decisions helps most.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "Opposite action: when frustration builds, try softening your tone on purpose — it de-escalates both of you.", "a_little_low": "Remind yourself that verbal negotiating, however exhausting, is a sign of real cognitive growth — not defiance for its own sake.", "okay": "Notice you''re adapting to a new stage of communication, even if it''s still a work in progress.", "good": "If a negotiation went smoothly today, notice what worked.", "really_good": "Enjoy the moments her growing language genuinely delights you."}'::jsonb,
  'A few minutes of quiet, wordless time for yourself after a day of negotiating.',
  'No specific note this week.',
  'Trade negotiating-strategy notes with another parent — you''re not the only one figuring this out.',
  'Navigating a smarter, more verbal toddler takes real adaptability — you''re building it.',
  'If low mood, anxiety, or feeling overwhelmed is continuing or worsening, open Mental health & support — help is there whenever you need it.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  147,
  'postpartum',
  'Potty Training, At Your Own Pace',
  'There''s no single right way to do this, or right time to start.',
  'If potty training is on your mind, approach it at whatever pace fits your child and your household.',
  'Potty training timelines vary enormously between children, and pressure from comparison — other kids, other families'' timelines — rarely helps. Whether you''re deep into it, just starting, or not ready yet, this week is about tuning out the noise and following what actually works for your child.',
  ARRAY['Pressure (external or self-imposed) around potty training timing','Frustration with setbacks, which are a completely normal part of the process','Relief when it clicks, even partially','No interest in starting yet, which is also completely fine']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "A few calming breaths after a frustrating accident or setback.", "steady": "A walk to decompress from the day''s ups and downs.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If a setback feels heavy, remind yourself accidents are a completely normal, expected part of learning — not a sign anything''s going wrong.", "a_little_low": "Comparing your child''s timeline to others'' rarely helps — every child gets there at their own pace.", "okay": "Notice today''s progress (or lack of it) without needing a verdict on the whole process.", "good": "A good day of progress is worth genuinely celebrating, however small.", "really_good": "Enjoy a real milestone moment fully."}'::jsonb,
  'Potty training can be relentless in the moment — a few minutes to yourself after a hard stretch is legitimate, not indulgent.',
  'No specific note this week.',
  'Ask another parent who''s been through it what actually helped them — real experience beats generic advice here.',
  'Wherever you are in this process, you''re handling it with patience most days — that''s real.',
  'However this week''s process felt, Mental health & support is there if you want more than a card can offer.',
  'If potty training is significantly delayed or regressing with other developmental concerns, your pediatrician can help assess whether anything else is going on. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  148,
  'postpartum',
  'The Return of Your Own Hobbies',
  'Something that''s just yours doesn''t need to justify itself.',
  'Revisit one hobby or interest that''s been dormant since before or during early motherhood.',
  'By two years in, many mothers find a little more bandwidth returning — enough, sometimes, to revisit an old interest or hobby that got shelved. This week is a gentle nudge to notice if that bandwidth exists for you, and to use it without guilt if it does.',
  ARRAY['A little more time or energy than earlier stages allowed','An old interest resurfacing, or curiosity about something new','Guilt about spending time on something "just for you"','No particular pull toward hobbies right now, which is also fine']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk, if you want space to think about what you''d revisit.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If guilt about wanting time for yourself feels heavy, remind yourself a fuller you is genuinely better for her too — this isn''t selfish, it''s sustainable.", "a_little_low": "A small step toward an old interest, even five minutes, can lift a flat mood more than you''d expect.", "okay": "Notice whether a hobby genuinely calls to you today, without forcing it.", "good": "If you spent any time on something just for you today, let that count fully.", "really_good": "Enjoy time in a hobby without any productivity pressure attached to it."}'::jsonb,
  'Give yourself real permission this week to spend time on something with no purpose beyond enjoying it.',
  'Revisit one hobby or interest, even briefly, and notice how it feels.',
  'Ask someone to cover childcare for a stretch specifically so you can do something that''s just yours.',
  'Finding your way back to something that''s just yours, after everything the last two years have asked of you, is real.',
  'If low mood, anxiety, or feeling flat is continuing or worsening, Mental health & support can help you take the next step.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  149,
  'postpartum',
  'Preschool or Not Preschool',
  'There''s no single right answer here — only what''s right for your family.',
  'If this decision is on your mind, give it honest thought without external pressure.',
  'Around this age, many families start considering preschool or structured daycare — a genuinely personal decision shaped by finances, family support, your child''s temperament, and your own preferences. There''s no universally "right" choice, only what fits your actual circumstances.',
  ARRAY['Pressure from others about when or whether to start preschool','Practical considerations (cost, logistics, availability) weighing heavily','Excitement or anxiety about the transition, if you''re moving forward with it','Complete contentment with your current setup, which is equally valid']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk, if you want space to think this through.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If this decision feels heavy, remember it doesn''t need to be solved today — a small amount of research or one conversation is enough progress for now.", "a_little_low": "If others'' opinions about preschool timing are weighing on you, remember this is your family''s decision, shaped by your actual circumstances, not anyone else''s.", "okay": "Notice where you honestly stand on this today, without needing certainty.", "good": "If today brought any clarity, let that count.", "really_good": "Whatever direction you''re leaning, let yourself feel good about it fully."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'Talk to your partner or a trusted friend about this decision — outside perspective can help clarify your own thinking.',
  'Thinking this through carefully, at your own pace, is exactly the right approach.',
  'However this decision feels, Mental health & support is there for anything it stirs up.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  150,
  'postpartum',
  'The Comparison Trap',
  'Her timeline is hers. Yours was always going to be different, too.',
  'Notice one comparison you''ve been making, and set it down, even briefly.',
  'Comparing your child''s milestones, behavior, or your own parenting to other families is nearly universal — and rarely helpful. This week is about noticing when comparison creeps in and gently choosing to step back from it.',
  ARRAY['Comparing her development, behavior, or habits to other children''s','Comparing your own parenting choices or capacity to other mothers''','Relief when you catch yourself and choose to let a comparison go','Genuine confidence in your own path, on the days that comes easily']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk without your phone — less exposure to comparison triggers.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "Cognitive defusion: when a comparison thought shows up, try \"I''m having the thought that...\" before it — it creates distance from a thought that''s steering your mood.", "a_little_low": "Remind yourself every child''s timeline is genuinely, legitimately different — comparison rarely reflects anything real about your child or your parenting.", "okay": "Notice today without measuring it against anyone else''s version of \"doing well.\"", "good": "If you caught and released a comparison today, that''s a real, practiced skill.", "really_good": "Enjoy confidence in your own path, fully, without needing anyone else''s validation."}'::jsonb,
  'Consider a short break from sources of comparison (social media, certain conversations) if they''re weighing on you this week.',
  'No specific note this week.',
  'Talk to a trusted friend about comparison pressures — chances are they feel it too, and naming it together helps.',
  'Choosing your own path, even amid constant comparison pressure, takes real steadiness.',
  'If comparison or low mood is weighing on you and not lifting, Mental health & support can help you take the next step.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  151,
  'postpartum',
  'Your Body, Three Years On',
  'Three years is a long time. Your body has been present for all of it.',
  'Notice your body honestly this week, appreciation and any concerns both.',
  'Nearly three years since pregnancy began, your body has been through an enormous amount — carrying, birthing, recovering, and the ongoing physical demands of caring for a toddler. This week is a check-in, both appreciative and practical.',
  ARRAY['A body that feels settled and familiar again, or still in flux','Lingering physical symptoms you may not have mentioned to a doctor','A different relationship with your body than before pregnancy','Genuine appreciation for what your body has carried you through']::text[],
  '{"focus": "Whatever your body genuinely wants this week.", "tiers": {"heavy": "Gentle stretching, paying attention to how your body actually feels.", "steady": "A walk, noticing your body rather than just getting through it.", "feeling_good": "A full session of your choice."}, "mood_adjustment": "If something physical has been bothering you, this is a good week to actually address it.", "safety": "Persistent symptoms — pain, unusual fatigue, anything that concerns you — are worth raising with your doctor rather than assuming they''re permanent."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "A self-compassion break: hand on heart, \"this body has carried us both through three years, and it''s allowed to still be figuring itself out.\"", "a_little_low": "Write down one physical thing you''ve been putting off mentioning to a doctor, and consider making that call this week.", "okay": "Notice your body neutrally — neither praising nor criticizing, just acknowledging it.", "good": "If you feel genuinely good in your body today, let that be enough.", "really_good": "Enjoy feeling strong or comfortable in your body fully."}'::jsonb,
  'Address one small physical thing you''ve been ignoring.',
  'No specific note this week.',
  'Talk to your partner or a friend about how your body feels, three years on.',
  'Your body has done an extraordinary amount over these three years. That deserves real acknowledgment.',
  'If body-related thoughts are weighing heavily and not lifting, Mental health & support can help.',
  'If anything physical has felt "off" for a while, bring it up specifically at your next visit rather than assuming it''s permanent. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  152,
  'postpartum',
  'Money Check-In, Six Months In',
  'A regular look at the numbers beats a constant background worry.',
  'A short, concrete financial check-in this week.',
  'Six months since the last dedicated money check-in (Week 91), this is another short pause to look honestly at your household''s financial picture — not to panic, but to stay ahead of it.',
  ARRAY['Costs that have shifted since your last check-in','Relief or stress depending on how things have moved','Avoidance if this feels overwhelming to look at','A wish for more structure around your finances']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "A few calming breaths before a financial task, if it feels stressful.", "steady": "A short walk before or after a financial task.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "Name the specific worry rather than letting it stay a vague dread — specificity makes it more workable.", "a_little_low": "One small task can turn worry into information, which is easier to carry than uncertainty.", "okay": "Notice financial stress doesn''t need solving today — one step is enough.", "good": "If you took a concrete step today, note the relief.", "really_good": "Use a good day to tackle something financial you''ve been avoiding."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'Have a shared, honest look at finances with your partner or household this week.',
  'Facing financial check-ins regularly, even in small ways, is real financial care.',
  'If financial stress is significantly affecting your mood, Mental health & support and the Wealth pillar''s planner can both help.',
  'No specific note this week — the Wealth pillar''s planner and schemes directory are built for exactly this. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  153,
  'postpartum',
  'Second-Sibling Thoughts, Revisited',
  'This is still your decision to make, whenever and however it evolves.',
  'If second-child thoughts are evolving, give them fresh honest space.',
  'Whatever you were thinking at Week 94, thoughts about another child (or firmly not) often continue evolving through the third year. This week is a fresh, honest check-in, wherever you currently stand.',
  ARRAY['Feelings that have shifted since you last thought about this seriously','Continued clarity, in whichever direction','New pressures or considerations that have entered the picture','Complete disinterest in revisiting the topic right now, which is fine too']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk, if you want space to think.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If this topic feels heavy, sit with it gently rather than rushing past it.", "a_little_low": "Remember this decision belongs to you (and your partner, if applicable) alone.", "okay": "Notice where you honestly stand today, without needing a final answer.", "good": "If clarity feels good today, whatever the direction, let that be enough.", "really_good": "Whatever you''re leaning toward, let it feel genuinely good."}'::jsonb,
  'Give yourself permission to not have a final answer.',
  'Reflect privately on what you actually want here.',
  'An honest conversation with a partner, if you have one, can help without needing to resolve everything at once.',
  'Continuing to think this through honestly, at your own pace, is exactly right.',
  'Whatever this topic brings up, Mental health & support is there if you want to talk it through.',
  'If you''re actively planning for or against another pregnancy, your doctor can help with timing and any relevant health considerations. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  154,
  'postpartum',
  'Screen Habits, Revisited',
  'Whatever''s working for your household right now is enough.',
  'A fresh, judgment-free look at your household''s current screen habits.',
  'Screen habits often shift as a child gets older and more capable — different content, different amounts, different triggers for guilt. This week is a fresh, honest look, same spirit as Week 87, adjusted for wherever you are now.',
  ARRAY['Screen habits that have shifted since earlier check-ins','New guilt triggers, or old ones resolving','Genuine relief in whatever balance you''ve found','A wish for more clarity, still']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk during a screen window, if one opens.", "feeling_good": "A full session while screens cover the gap."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'A screen window is a legitimate rest window for you too.',
  '{"heavy_day": "If screen guilt feels heavy, remind yourself a rested parent tomorrow matters more than a screen-free hour today.", "a_little_low": "Notice your household''s actual pattern without comparing it to anyone else''s.", "okay": "No specific note this week.", "good": "If today''s balance felt right, that''s the only standard that matters.", "really_good": "Enjoy a good day without needing to justify it."}'::jsonb,
  'Use a guilt-free screen window for something genuinely restorative.',
  'No specific note this week.',
  'Talk to your partner about what feels right for your household now.',
  'Continuing to navigate this thoughtfully, rather than on autopilot, is real parenting work.',
  'No specific note this week beyond the persistent support link below.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  155,
  'postpartum',
  'The Mental Load, Revisited',
  'Naming it again doesn''t mean you failed to fix it the first time.',
  'A fresh check-in on how the mental load is currently distributed in your household.',
  'Mental load distribution (Week 98) often needs revisiting as household demands shift. This week is a fresh, honest look — not because the last conversation failed, but because these things need periodic re-checking.',
  ARRAY['Whether previous conversations about the mental load actually shifted anything','New areas of invisible work that have emerged','Relief where things have genuinely improved','Frustration where old patterns have crept back']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "A few minutes stepping away from the running list in your head.", "steady": "A walk without your phone.", "feeling_good": "Whatever gives you real mental space."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'Mental rest matters as much as physical rest.',
  '{"heavy_day": "Write the whole list down — externalizing it out of your head reduces the weight of carrying it silently.", "a_little_low": "Naming it out loud again, even if you''ve said it before, isn''t nagging — it''s maintenance.", "okay": "Notice today''s load honestly.", "good": "If someone shared the load today, notice and appreciate it.", "really_good": "Enjoy a day where the load felt lighter, and notice what made it so."}'::jsonb,
  'Delegate one thing this week, even imperfectly done by someone else.',
  'No specific note this week.',
  'Have another direct conversation about dividing the mental load — revisiting isn''t failure, it''s normal maintenance.',
  'Continuing to advocate for a fairer distribution of invisible work, even when it takes repeating, is real, worthwhile effort.',
  'If the mental load is contributing to ongoing low mood or overwhelm, Mental health & support can help.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  156,
  'postpartum',
  'Sleep, Three Years In',
  'However sleep looks right now, it''s allowed to still be a work in progress.',
  'An honest look at your own sleep, not just hers.',
  'Three years in, sleep — hers and yours — may still be inconsistent, or may have found a genuinely good rhythm. Either way, this week is a check-in on your own sleep specifically, which often gets overlooked once a child''s sleep improves.',
  ARRAY['Your own sleep quality, separate from hers','Old sleep-deprivation habits (late scrolling, poor wind-down) that never fully broke','A genuinely restored sleep rhythm, worth noticing','Ongoing fatigue even with adequate hours, which may be worth mentioning to a doctor']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "Gentle stretching before bed, especially if sleep has been poor.", "steady": "A walk earlier in the day — supports better sleep at night.", "feeling_good": "Whatever movement you enjoy, ideally not too close to bedtime."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'If your own sleep habits (screens, late nights) have never fully reset since early motherhood, this is a good week to notice and gently adjust one of them.',
  '{"heavy_day": "Progressive muscle relaxation before bed: tense your shoulders for 5 seconds, then release. A real, simple technique for easing into sleep.", "a_little_low": "If persistent low mood is affecting your sleep, or poor sleep is affecting your mood, that''s worth naming to your doctor rather than assuming it''s permanent.", "okay": "No specific note this week.", "good": "If sleep has genuinely improved, let yourself notice and enjoy that.", "really_good": "Enjoy feeling rested — it''s not something to take for granted after three years of disrupted sleep."}'::jsonb,
  'Protect one small piece of a wind-down routine tonight, even five minutes.',
  'No specific note this week.',
  'No specific note this week.',
  'Three years of navigating sleep — yours and hers — is real, ongoing work.',
  'If sleep and mood have both felt off together, Mental health & support can help you think through what''s going on.',
  'If ongoing fatigue doesn''t improve with adequate sleep, mention it at your next check-up — it''s worth ruling out anything beyond typical parental tiredness. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  157,
  'postpartum',
  'Public Meltdowns, Evolved',
  'A meltdown in public says nothing about your parenting.',
  'Have one calming strategy ready before you need it in public.',
  'Public meltdowns don''t disappear at two or three — they just look different, sometimes trickier since a more verbal child can also argue back. This week is about having a real strategy ready, and letting go of any embarrassment about how it looks to others.',
  ARRAY['Public meltdowns that feel different from the toddler-tantrum stage','Self-consciousness about how it looks to strangers','Frustration when old strategies stop working','Growing confidence in handling hard public moments, on good days']::text[],
  '{"focus": "Something that discharges tension after a hard public moment.", "tiers": {"heavy": "Shake out your hands and arms after a hard moment — releases physical stress quickly.", "steady": "A walk, especially right after a difficult moment if you can step away.", "feeling_good": "Whatever exercise helps you feel steady this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "Box breathing before responding: in for 4, hold for 4, out for 4 — helps you stay regulated so you can stay steady for her.", "a_little_low": "A public meltdown reflects her age and development, not your parenting — that''s not a platitude, it''s what the research shows.", "okay": "Notice you handled today''s moments reasonably well, even imperfectly.", "good": "If you stayed calm through a hard public moment today, that''s a real, hard-won skill.", "really_good": "Notice how much easier this has genuinely gotten since the early toddler years."}'::jsonb,
  'A cool drink or a moment of quiet after a hard public moment — a small physical reset.',
  'No specific note this week.',
  'If public meltdowns are wearing on you, tell someone close specifically what would help.',
  'Staying steady through public hard moments, again and again, regardless of who''s watching, is real strength.',
  'No specific note this week beyond the persistent support link below.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  158,
  'postpartum',
  'Rediscovering Intimacy and Partnership',
  'Whatever connection looks like right now, it''s allowed to be rebuilt slowly.',
  'One small, real moment of intimacy or partnership this week, whatever shape fits you.',
  'Three years in, romantic and partnership intimacy can still feel different from before children — genuinely worth revisiting rather than assuming it will simply return on its own. This week is a gentle nudge, not a demand.',
  ARRAY['A partnership that feels more like co-management than romance','A wish for more connection than your days currently allow','Genuine reconnection happening naturally, which is worth noticing','Complexity if you''re parenting solo, where this theme may look different']::text[],
  '{"focus": "Movement you could share, if you want to.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk with a partner, if that fits.", "feeling_good": "A shared activity, if your schedules allow."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If this topic feels heavy, that''s okay — a single honest conversation starter counts as reaching out.", "a_little_low": "Disconnection after young children is common — naming it to a partner, gently, is a real first step.", "okay": "Notice one moment of real connection today, even small.", "good": "If today included a genuine moment of connection, let it count.", "really_good": "Plan something slightly bigger for connection soon, while the energy is there."}'::jsonb,
  'Connection with yourself counts too, if that''s what this week calls for.',
  'No specific note this week.',
  'Reach out specifically to reconnect this week — not about logistics, just connection.',
  'Investing in connection during a demanding stage of life is genuinely worthwhile.',
  'If relationship strain is significantly affecting your wellbeing, Mental health & support can help you think through next steps.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  159,
  'postpartum',
  'Your Career, One More Look',
  'There''s no deadline on figuring this out.',
  'A fresh, pressure-free look at where you stand on work and career.',
  'Career and identity questions (Week 96) often continue evolving through year three. This week is a fresh check-in, wherever you currently stand — no deadline, no verdict required.',
  ARRAY['Continued pull toward paid work, or a different kind of work','Contentment with your current path, still valid','New clarity that''s emerged since your last check-in','Ongoing uncertainty, which is also a fine place to be']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk, if you want space to think this through.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If career uncertainty feels heavy, remember it doesn''t need resolving today.", "a_little_low": "If comparison to others'' paths is weighing on you, remember every path looks different.", "okay": "Notice where you honestly stand today, without needing certainty.", "good": "If today brought any clarity or a small step forward, let that count.", "really_good": "Whatever direction you''re moving in, feel good about it fully."}'::jsonb,
  'Remind yourself your worth isn''t measured by employment status.',
  'Spend a few minutes exploring one interest or skill.',
  'Talk to your partner or a trusted friend about what you''re thinking through.',
  'Continuing to think honestly about your own path takes real intention.',
  'No specific note this week beyond the persistent support link below.',
  'No specific note this week — Library book *Creating Your Own Opportunities* covers this territory in depth if you want to go further. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  160,
  'postpartum',
  'How Are You, Really',
  'Almost three years in, checking on yourself is still allowed.',
  'An honest, no-judgment check-in on how you''ve actually been doing.',
  'This is a dedicated pause to ask how you''re really doing — same spirit as Weeks 88 and 100. This project deliberately doesn''t use the term "postpartum depression" this far out, since the window that term is grounded in has long passed — but ongoing low mood, anxiety, or feeling flat for weeks at a time is still worth taking seriously, at any point in motherhood.',
  ARRAY['Genuinely doing okay, worth noticing too, not just hard stretches','A low mood or heaviness that''s lasted longer than a bad week','A sense that yourself has quietly slipped further away','Uncertainty about whether what you''re feeling is worth mentioning to someone']::text[],
  '{"focus": "Movement this week is optional and secondary to the check-in itself.", "tiers": {"heavy": "A few slow breaths before anything else today.", "steady": "A walk alone, with space to think about how you''re doing.", "feeling_good": "Whatever movement feels good — this week the real work is elsewhere."}, "mood_adjustment": "No specific note this week — see the honest check-in below instead.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'If exhaustion has felt constant rather than tied to a hard week, that''s worth mentioning below, not just accepting as permanent.',
  '{"heavy_day": "If today is heavy, and this has been a longer pattern, it''s worth reading more about what ongoing low mood or anxiety can look like at this stage, and talking to your doctor or someone you trust. There''s no point at which it''s \"too late\" to ask for support.", "a_little_low": "A little low, if it''s been the pattern more often than not lately, deserves honest attention.", "okay": "If you''re genuinely okay, trust that.", "good": "If you''re doing well, notice what''s been helping.", "really_good": "A really good stretch is worth celebrating fully."}'::jsonb,
  'Whatever your honest answer this week, offer yourself the same care you''d offer a close friend.',
  'Take a few minutes to actually sit with the question "how am I, really."',
  'If this check-in surfaced something heavier than expected, the "Help me prepare to talk to someone" tool in Mental health & support can help you put it into words.',
  'Nearly three years of showing up, in whatever way you have, is a real and significant thing.',
  'If low mood, anxiety, or persistent exhaustion has been ongoing, please don''t wait to reach out — Mental health & support can help you take the next step.',
  'If low mood, anxiety, or persistent exhaustion has been ongoing, raise it directly at your next appointment — maternal mental health support has no expiry date. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  161,
  'postpartum',
  'Grandparents and Extended Family, Evolving',
  'Roles shift as she grows. You''re allowed to shape how, together.',
  'Notice one extended-family dynamic that''s shifted, and how you feel about it.',
  'As your child grows more independent and interactive, relationships with grandparents and extended family often shift too — sometimes closer, sometimes more complicated. This week is about noticing these dynamics honestly.',
  ARRAY['Grandparent relationships deepening as she becomes more interactive','Ongoing tension or disagreement about parenting approaches','Gratitude for family support, where it exists','Complexity if family dynamics are difficult or distant']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "A few calming breaths before a difficult family conversation, if one''s coming up.", "steady": "A walk to process any family tension.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "A short self-compassion break before responding to family tension — \"this is hard, and I''m allowed to protect my peace.\"", "a_little_low": "If a strained family relationship feels heavy, that''s valid — family dynamics don''t automatically resolve just because time has passed.", "okay": "Notice today''s family interactions honestly.", "good": "If a family interaction went well today, note that.", "really_good": "Enjoy a family moment that felt genuinely easy."}'::jsonb,
  'No specific note this week.',
  'Reflect on which family relationships feel nourishing right now, and which need boundaries.',
  'If a family dynamic feels hard, talk it through with your partner or a trusted friend.',
  'Navigating family relationships thoughtfully, rather than by default, is real, ongoing work.',
  'If family stress is significantly affecting your wellbeing, Mental health & support can help.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  162,
  'postpartum',
  'Illness Season, Again',
  'Catching what she brings home is exposure, not a failing immune system.',
  'Take your own symptoms as seriously as hers, same as always.',
  'Illness season cycles back around, same as it did at Week 86 — preschool or playgroup exposure, your own still-adjusting immune system, and the genuine challenge of caring for a sick child while unwell yourself.',
  ARRAY['Catching what she brings home, again','Pushing through your own illness because there''s no obvious backup','Guilt about resting while she still needs care','Slower recovery than you''d like']::text[],
  '{"focus": "Rest is the priority if you''re unwell.", "tiers": {"heavy": "If you''re sick, skip movement and prioritize rest.", "steady": "Gentle stretching only if genuinely recovering.", "feeling_good": "Ease back in once you''re actually better, not before."}, "mood_adjustment": "If unwell, \"movement\" means rest this week.", "safety": "Avoid pushing through fever, significant fatigue, or any symptoms your doctor would want to know about."}'::jsonb,
  'Simple, easy-to-digest food if you''re unwell.',
  'Extra fluids if you or your toddler are sick.',
  'No specific note this week.',
  'Ask for backup this week if you''re sick — not optional, necessary.',
  '{"heavy_day": "If you''re running on empty from illness, a short self-compassion break can help before problem-solving anything.", "a_little_low": "Lower every expectation this week if illness is in the house — survival mode is appropriate, not a failure.", "okay": "If you''re recovering, notice that gently, without rushing back to full pace.", "good": "A healthy day after an illness stretch is worth genuinely appreciating.", "really_good": "Enjoy the return to normal energy — it''s earned."}'::jsonb,
  'Basic comfort — warm drinks, rest — is the priority if unwell.',
  'Even sick, five minutes of something calming can help.',
  'Actually ask for help this week if illness hits your household.',
  'Getting through an illness stretch with everyone cared for is real work.',
  'No specific note this week beyond the persistent support link below.',
  'If you''re frequently catching what she brings home, mention it at your next check-up. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  163,
  'postpartum',
  'Your Own Friendships, Three Years In',
  'Some friendships found their footing again. Notice which ones did.',
  'Notice which friendships genuinely feel nourishing now, three years in.',
  'Friendships (Week 92) often settle into a new, more stable shape by three years in — some rebuilt, some newly formed through motherhood, some gently let go of. This week is an honest check-in on where things stand.',
  ARRAY['Friendships that have found solid footing again','New friendships formed through motherhood that have become genuinely important','Continued gaps you''d like to fill','Gratitude for whoever has consistently shown up']::text[],
  '{"focus": "Movement you could share with a friend, if the opportunity arises.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk with a friend, in person or by phone.", "feeling_good": "A shared activity with a friend, if schedules allow."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If loneliness feels heavy, remind yourself friendship shifts are common after having a child, not a personal failing.", "a_little_low": "Reach out to one friend you''ve been meaning to message.", "okay": "Notice your current friendships honestly.", "good": "If a friendship felt good today, enjoy it fully.", "really_good": "Make a plan to see or talk to a friend soon."}'::jsonb,
  'Investing in a nourishing friendship is a form of self-care.',
  'Reflect on which friendships genuinely fill you up now.',
  'Reach out to one person specifically to maintain or deepen a connection.',
  'Nurturing friendships across three demanding years takes real, ongoing effort.',
  'No specific note this week beyond the persistent support link below.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  164,
  'postpartum',
  'Boundaries, Revisited',
  'A boundary set once may need setting again. That''s normal, not failure.',
  'Revisit one boundary (with family, friends, or work) that needs reinforcing.',
  'Boundaries set earlier (Week 97) sometimes need reinforcing as circumstances change or old patterns creep back. This week is a fresh, non-judgmental look at where a boundary might need a repeat conversation.',
  ARRAY['A boundary that''s held well, worth noting','A boundary that''s eroded and needs reinforcing','Guilt about needing to repeat yourself','Growing confidence in setting boundaries generally, three years in']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "A few calming breaths before a boundary conversation, if one''s needed.", "steady": "A walk to clarify what you need to say.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "A self-compassion break before responding — \"this is hard, and I''m allowed to protect my peace, even if I''ve said this before.\"", "a_little_low": "Guilt about repeating a boundary is common — it doesn''t mean the first attempt failed, it means it needs reinforcing.", "okay": "Notice today''s boundaries honestly, without needing to fix everything at once.", "good": "If a boundary was respected today, note that.", "really_good": "Enjoy an interaction that felt genuinely easy."}'::jsonb,
  'Practicing a boundary again, even privately first, builds the muscle.',
  'No specific note this week.',
  'If reinforcing a boundary alone feels hard, ask your partner to back you up.',
  'Protecting your own choices, even when it takes repeating, is a genuine act of strength.',
  'No specific note this week beyond the persistent support link below.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  165,
  'postpartum',
  'Preparing for the Next Transition',
  'Whatever''s coming next, you''ve navigated transitions before.',
  'If a transition (preschool, a new routine, a move) is coming up, prepare at a pace that fits you both.',
  'Whether it''s starting preschool, a new daycare routine, or another change on the horizon, this week is about preparing thoughtfully rather than anxiously — trusting that you''ve navigated real transitions before, and you''ll navigate this one too.',
  ARRAY['Anticipation or anxiety about an upcoming change','Practical logistics competing for your energy','Confidence, if you''ve been through similar transitions before','No major transition on the horizon, which is also fine — read this week loosely']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "A few calming breaths if transition-planning feels stressful.", "steady": "A walk to think through logistics without pressure.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If transition-planning feels heavy, remind yourself you''ve handled real change before, and you''ll handle this too.", "a_little_low": "Break the transition into one small next step rather than the whole picture at once.", "okay": "Notice where planning stands today, without needing it finished.", "good": "If a piece came together easily today, enjoy that.", "really_good": "Look forward to what''s ahead, whatever shape it takes."}'::jsonb,
  'Keep planning simple enough that you''ll actually enjoy the transition, not just survive planning it.',
  'No specific note this week.',
  'Delegate at least one piece of the planning to someone else.',
  'Preparing thoughtfully for what''s next, rather than reactively, is real, considered parenting.',
  'If transition anxiety is significant, Mental health & support can help.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  166,
  'postpartum',
  'Your Evolving Identity as a Mother',
  'Who you are as a mother keeps changing. That''s not instability — it''s growth.',
  'Notice how your own sense of "mother" has shifted over these three years.',
  'The version of yourself as a mother now is likely quite different from who you were in the newborn weeks, or even a year ago. This week is a pause to notice that evolution, rather than measuring yourself against an earlier, fixed idea of who you thought you''d be.',
  ARRAY['A version of yourself as a mother that''s grown considerably since the start','Old expectations of motherhood that no longer fit who you''ve become','Pride in the mother you''ve grown into','Continued uncertainty about identity, which is also completely normal']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk, with space to reflect on this.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If this reflection feels heavy, that''s valid — identity questions can bring up real grief for who you were before, alongside pride in who you''ve become.", "a_little_low": "Notice one way you''ve genuinely grown as a mother, even on a low day.", "okay": "Notice your identity as a mother honestly today, without needing a tidy narrative.", "good": "Let yourself feel genuinely proud of the mother you''ve become.", "really_good": "Celebrate this evolution fully, without minimizing it."}'::jsonb,
  'Do something this week that marks this reflection, just for you.',
  'Write down, even briefly, how your sense of yourself as a mother has changed.',
  'Share this reflection with someone who''s known you across this whole journey.',
  'Growing into the mother you are now, through everything these three years have held, is genuinely something to be proud of.',
  'If identity questions are bringing up real distress, Mental health & support can help.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  167,
  'postpartum',
  'Rest, Redefined',
  'Rest doesn''t have to mean doing nothing. It means whatever actually restores you.',
  'Notice what genuinely restores you now, which may be different from what did earlier.',
  'What counted as "rest" in the newborn weeks (sleep, mostly) looks different three years in — sometimes it''s stillness, sometimes it''s an activity that fully absorbs you. This week is about noticing what actually restores you now.',
  ARRAY['A clearer sense of what genuinely restores you these days','Old ideas about rest (just sleep, just stillness) that no longer fully apply','Guilt about "rest" that doesn''t look like doing nothing','A wish for more real rest than your days currently allow']::text[],
  '{"focus": "Whatever counts as rest and restoration for you specifically.", "tiers": {"heavy": "Whatever five minutes genuinely restores you, movement or stillness both count.", "steady": "Your version of restorative time.", "feeling_good": "A fuller version of whatever restores you."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'Rest doesn''t have to mean stillness — whatever genuinely restores you counts, even if it''s active.',
  '{"heavy_day": "A gratitude practice, brief version: name one small thing you''re grateful for right now, even amid a hard day — it doesn''t erase the hard, but it can widen the frame slightly.", "a_little_low": "Notice what you actually crave right now — rest may look different than you''d expect.", "okay": "Notice today without needing more from it.", "good": "If you found real rest today, notice what it looked like.", "really_good": "Enjoy feeling genuinely restored."}'::jsonb,
  'Choose your own version of rest this week, even if it doesn''t look like "traditional" rest.',
  'Reflect on what genuinely restores you these days.',
  'No specific note this week.',
  'Learning what actually restores you, three years in, is real self-knowledge.',
  'No specific note this week beyond the persistent support link below.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  168,
  'postpartum',
  'Toddler Independence, Big Leaps',
  'Every leap she takes is one more sign she''s ready for the next stage.',
  'Notice one area where she''s genuinely ready for more independence, and let her have it.',
  'By nearly three, independence leaps come faster — dressing herself, making choices, doing things without help she once needed. This week is about noticing and supporting these leaps, even when they''re slower or messier than doing it yourself.',
  ARRAY['Real, visible growth in what she can do independently','A pull to step in and do it faster','Pride mixed with a small sense of loss at how much less she needs you for','Your own growing independence in parallel, worth noticing too']::text[],
  '{"focus": "Something you choose entirely on your own terms.", "tiers": {"heavy": "A few minutes of movement chosen entirely by you.", "steady": "A walk alone, a small taste of independence in your own day.", "feeling_good": "A full session of something that''s entirely your own choice."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If the slower pace of her independence tests your patience, box breathing before stepping in can help you wait a beat longer.", "a_little_low": "Notice any bittersweet feelings about her needing you less — both the pride and the small grief are valid.", "okay": "Notice a moment today where you let go a little.", "good": "If you watched her succeed at something new today, let that pride be fully yours too.", "really_good": "Celebrate her growing independence, fully."}'::jsonb,
  'Do one thing entirely on your own terms this week.',
  'Reflect on your own growing independence, alongside hers.',
  'Ask for a stretch of time this week that''s entirely your own.',
  'Watching her grow more independent, while continuing to nurture your own, is a real, ongoing balancing act.',
  'No specific note this week beyond the persistent support link below.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  169,
  'postpartum',
  'Reflecting on Almost Three Years',
  'You don''t need a perfect record to have done this well.',
  'Take real stock of the journey so far, as the third birthday approaches.',
  'As you head into the final stretch before the third birthday, this week is a genuine pause to reflect — not to judge, but to notice how far you''ve both come across nearly three full years.',
  ARRAY['A mix of pride and disbelief looking back','Memories of the hardest stretches resurfacing','Gratitude for people, moments, or your own resilience','A sense that time has moved impossibly fast and painfully slow, both']::text[],
  '{"focus": "No specific movement theme this week.", "tiers": {"heavy": "No specific note this week.", "steady": "A walk, with space to reflect on the journey so far.", "feeling_good": "Whatever movement you enjoy this week."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "If looking back brings up hard memories, that''s valid — you''re allowed to acknowledge how hard parts of this journey genuinely were.", "a_little_low": "If nostalgia or grief for earlier stages shows up, both can coexist with being glad to be where you are now.", "okay": "Notice the journey honestly, without needing a tidy narrative.", "good": "Let yourself feel genuinely proud of one specific thing from this journey.", "really_good": "Celebrate how far you''ve both come, fully."}'::jsonb,
  'Do something this week that marks this milestone just for you.',
  'Write down, even briefly, what you''re most proud of from this whole journey.',
  'Share a reflection or memory from this journey with someone who was there for it.',
  'Nearly three years of mothering, through everything this journey has held, is genuinely something to be proud of.',
  'No specific note this week beyond the persistent support link below.',
  'No specific note this week. — — — — — — — — — — — — — — — — — — — — — — — — --',
  null
),
(
  170,
  'postpartum',
  'Halfway to Three',
  'The final stretch is here. You''ve carried this far, and you''ll carry it home.',
  'Notice you''re in the home stretch of this three-year journey, and let that land.',
  'This closes the first half of Your Rhythm, Year Three — six months out from the third birthday. Part 2 of this phase will carry you through to that final milestone. For now, this week is a chance to pause at the halfway point of this final stretch.',
  ARRAY['A real sense of nearing the end of this particular chapter','Continued demands, even amid the milestone feeling','Anticipation about what comes after the third birthday','Pride in having sustained this rhythm for so long']::text[],
  '{"focus": "Whatever routine has genuinely served you through this stretch.", "tiers": {"heavy": "A few stretches, wherever you are.", "steady": "Your established walk or short session.", "feeling_good": "Your established routine, at whatever level fits."}, "mood_adjustment": "No specific note this week.", "safety": "No specific caution this week."}'::jsonb,
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  'No specific note this week.',
  '{"heavy_day": "Box breathing: in for 4, hold for 4, out for 4, hold for 4 — a reliable reset, worth returning to whenever needed.", "a_little_low": "Notice this stretch is nearly done, even on a low day — the finish line for this particular chapter is close.", "okay": "Notice today as simply okay, part of the ongoing rhythm.", "good": "Let a good day be good, fully.", "really_good": "Enjoy being this far into the journey."}'::jsonb,
  'Whatever ritual has stuck for you by now, keep it going into this final stretch.',
  'Reflect on the six months ahead, and what you''d like them to hold.',
  'Tell someone close how much closer you are to this milestone now.',
  'Halfway through the final stretch — you''ve sustained this for nearly two and a half years. That''s real endurance.',
  'However this week felt, support isn''t limited to hard weeks — Mental health & support is there whenever it''s useful to you.',
  'No specific note this week beyond the long-term reminders below.',
  '[{"flag": "diabetes_gd", "note": "If your pregnancy involved gestational diabetes, ADA and ACOG guidance recommends ongoing screening for type 2 diabetes every 1 to 3 years, for life — this is a good moment to confirm with your doctor when your next screening is due."}, {"flag": "high_bp", "note": "If you had high blood pressure during pregnancy or postpartum, keep that history on your medical record permanently — make sure your regular doctor knows about it as part of your ongoing cardiovascular care."}, {"flag": "thyroid", "note": "If you have a thyroid condition, continued monitoring stays relevant — keep up with your prescribed treatment and routine labs."}, {"flag": "pcos", "note": "If you have PCOS, this is a reasonable time to revisit your own metabolic and cycle health with your doctor, separate from anything related to pregnancy or breastfeeding. — — — — — — — — — — — — — — — — — — — — — — — — --"}]'::jsonb
);
